{% set name = "x265" %}
{% set version = "2.8" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "6e59f9afc0c2b87a46f98e33b5159d56ffb3558a49d8e3d79cb7fdc6b7aaa863" %}

package:
  name: '{{ name }}'
  version: '{{ version }}'

source:
  fn: x265_{{ version }}.tar.gz
  url: http://ftp.videolan.org/pub/videolan/x265/x265_{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  skip: true         # [win]

requirements:
  build:
    - yasm
    - nasm
    - cmake

test:
  commands:
    - test -f ${PREFIX}/include/x265.h
    - test -f ${PREFIX}/include/x265_config.h
    - test -f ${PREFIX}/lib/libx265.a
    - test -f ${PREFIX}/lib/libx265.so
    - x265 --version

about:
  home: https://bitbucket.org/multicoreware/x265/wiki/Home
  license: GPL 2
  license_file: COPYING
  summary: An open source HEVC encoder.

